### ISSUE TITLE
Adding a SO variable to a list in the inspector changes all elements of the list

### ISSUE THREAD

**Issue by CharredBaguette** [Brandon-Gui123/unity-scriptableobject-variables#6]
Dragging and dropping a ScriptableObject variable into a serialized list/array in the inspector causes all elements of that list/array to be changed to that same element.

**Comment by Brandon-Gui123** [comment]
Alright, I think I got it. Can you replace the `VariableReference_PropertyDrawer.cs` file with the one I just uploaded? Just extract the zip file and you will have the file.

[VariableReference_PropertyDrawer.zip](https://github.com/Brandon-Gui123/unity-scriptableobject-variables/files/4594341/VariableReference_PropertyDrawer.zip)

**Comment by CharredBaguette** [comment]
The issue is fixed. Dragging ScriptableObject variables into the list works as intended.
